### PR TITLE
Add merge sort Snippet

### PR DESCRIPTION
**Pull request by trishit78**
Created a Merge Sort Snippet, Can you have a look at this and if everything is okay, Can you merge it?

### CODE REVIEW

**Review by PrakashGatiyala — CHANGES_REQUESTED** [review]
xor-of-array.md file updated. why? There should only one file changed.

**Comment by trishit78** [comment]
xor-of-array.md file was updated by mistake . Nothing is changed , just tried to copy some md marks , got some extra spaces , that's it.
Should I re-upload then?

**Comment by PrakashGatiyala** [comment]
> xor-of-array.md file was updated by mistake . Nothing is changed , just tried to copy some md marks , got some extra spaces , that's it. Should I re-upload then?

Discard the changes for that file/

**Comment by PrakashGatiyala** [comment]
lgtm

**Pull request merged**
