### PR TITLE
added binary tree inorder traversal

### PR DESCRIPTION
**Pull request by Rishabhco**

### CODE REVIEW

**Review by PrakashGatiyala — APPROVED** [review]
Share your issue link.
Checkout guideline 
https://github.com/PrakashGatiyala/60-seconds-of-cpp/issues/33

**Review by Rishabhco — COMMENTED** [review]
changed the filename
#33

**Comment by PrakashGatiyala** [comment]
> changed the filename #33
Check this out. 
https://github.com/PrakashGatiyala/60-seconds-of-cpp/issues/34

**Comment by Rishabhco** [comment]
#36

**Review by PrakashGatiyala — CHANGES_REQUESTED** [review]
File format is .md. Check example https://github.com/PrakashGatiyala/60-seconds-of-cpp/blob/main/snippet-template.md or checkout existing snippet format.

**Review by Rishabhco — COMMENTED** [review]
updated the format
#36

**Review by PrakashGatiyala — APPROVED** [review]

**Pull request merged**
